name: wsg-courses-mcp-dev
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    # Production dependencies
    - fastapi>=0.100.0
    - mcp>=1.12.0
    - fastapi_mcp
    - pydantic>=2.0.0
    - pydantic-settings>=2.0.0
    - uvicorn[standard]>=0.24.0
    - gunicorn>=21.2.0
    - httpx>=0.25.0
    - requests>=2.31.0
    - python-dotenv>=1.0.0
    # Development dependencies
    - pytest>=7.4.0
    - pytest-asyncio>=0.21.0
    - pytest-cov>=4.1.0
    - pytest-mock>=3.12.0
    - black>=23.0.0
    - isort>=5.12.0
    - flake8>=6.0.0
    - mypy>=1.5.0
    - pre-commit>=3.5.0
